### ISSUE TITLE
Any plan to support neovim?

### ISSUE THREAD

**Issue by rawaludin** [yuttie/comfortable-motion.vim#5]

**Comment by yuttie** [comment]
Neovim is supported because actually I'm using Neovim for developing this plugin :)
So, it should work on your Neovim too, but if it doesn't, please open another issue.

I updated README.md (7130ce730cb0a14e0fce71a39daa0ca163ca711a) slightly so that you can see that Neovim is supported.

**Comment by rawaludin** [comment]
Anyway, I suggest you put git image somewhere else. Maybe another repo. So, we don't need to download gif image when installing this plugin.

**Comment by rawaludin** [comment]
Eg. @junegunn repo
https://github.com/junegunn/vim-easy-align

Gif is at
https://github.com/junegunn/i

**Comment by rawaludin** [comment]
Anyway, its working now. Really happy to have this plugin.. :)

**Comment by yuttie** [comment]
@rawaludin I'm glad to hear that :)

Thanks for your suggestion. I didn't know that `git clone` also downloads objects which don't belong to the target branch, and that's why I put those images in `gh-pages` branch.
I will move them to another place (a different repository or web site) later :)

Have fun!
