### ISSUE TITLE
Respect to &scroll value

### ISSUE THREAD

**Issue by markwu** [yuttie/comfortable-motion.vim#7]
It looks nice, but works weird. My screen height is 38 lines, when I press CTRL-F, it always over jump to 65 line, not 37 or 38 line.

It seems this plugin does not respect to &scroll value.

You may reference to terryma's implementation, it respect to &scroll value.

https://github.com/terryma/vim-smooth-scroll

**Comment by yuttie** [comment]
Yes, currently this plugin ignores the value. This is a limitation of the current implementation.

Because this plugin is physics-based, it's not trivial to adjust the initial speed of scrolling (that is passed to `comfortable_motion#flick()`) to get a desired amount of scroll.

I think it is inconvenient and it should be improved.

**Comment by yuttie** [comment]
I'm closing this issue because there is no active discussion.
Please feel free to re-open this issue, if you need.
